# Generated by Django 5.2.14 on 2026-06-01 04:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT", "Government"),
                            ("PRIVATE", "Private"),
                            ("NGO", "NGO / Aid Organisation"),
                            ("OTHER", "Other"),
                        ],
                        default="GOVERNMENT",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "funder_type",
                    models.CharField(
                        choices=[
                            ("OTML_TCS", "OTML / TCS"),
                            ("ADB", "ADB (Asian Development Bank)"),
                            ("WORLD_BANK", "World Bank"),
                            ("DFAT", "DFAT (Australia Aid)"),
                            ("PRIVATE", "Private"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funder",
                "verbose_name_plural": "Funders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building / Structural"),
                            ("CIVIL", "Civil Works"),
                            ("ELECTRICAL", "Electrical"),
                            ("EPC", "EPC (Engineering, Procurement & Construction)"),
                            ("MIXED", "Mixed / Multi-discipline"),
                        ],
                        default="BUILDING",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TENDERING", "Tendering"),
                            ("AWARDED", "Awarded"),
                            ("MOBILISATION", "Mobilisation"),
                            ("ACTIVE", "Active / Under Construction"),
                            ("PRACTICAL_COMPLETION", "Practical Completion"),
                            ("DEFECTS_LIABILITY", "Defects Liability Period"),
                            ("CLOSED", "Closed"),
                        ],
                        default="TENDERING",
                        max_length=30,
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("site_address", models.TextField(blank=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="GPS Latitude",
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="GPS Longitude",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/thumbnails/"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.funder",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "project_manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site_supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "site_supervisor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("CONTRACTUAL", "Contractual"),
                            ("INTERNAL", "Internal"),
                            ("FUNDER", "Funder / External"),
                        ],
                        default="CONTRACTUAL",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("is_achieved", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="milestones/evidence/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "ordering": ["project", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVariation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("ref_number", models.CharField(editable=False, max_length=30)),
                ("description", models.TextField()),
                ("date_instructed", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTRUCTED", "Instructed"),
                            ("SUBMITTED", "Submitted"),
                            ("ASSESSED", "Assessed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="INSTRUCTED",
                        max_length=20,
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[("ADD", "Addition"), ("OMIT", "Omission")],
                        default="ADD",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount (PGK)"
                    ),
                ),
                (
                    "supporting_document",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Variation",
                "verbose_name_plural": "historical Variations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DelayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "delay_type",
                    models.CharField(
                        choices=[
                            ("WEATHER", "Weather / Rainfall"),
                            ("MATERIAL", "Material Supply"),
                            ("DESIGN", "Design / Drawing Issue"),
                            ("CLIENT", "Client Instruction / Variation"),
                            ("LABOUR", "Labour Shortage"),
                            ("FORCE_MAJEURE", "Force Majeure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("CONTRACTOR", "Contractor"),
                            ("FORCE_MAJEURE", "Force Majeure"),
                        ],
                        default="CLIENT",
                        max_length=20,
                    ),
                ),
                (
                    "impact_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Impact (calendar days)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delay_events",
                        to="projects.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delay Event",
                "verbose_name_plural": "Delay Events",
                "ordering": ["project", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(blank=True, max_length=100)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("LUMP_SUM", "Lump Sum"),
                            ("SCHEDULE_OF_RATES", "Schedule of Rates"),
                            ("COST_PLUS", "Cost Plus"),
                            ("EPC", "EPC"),
                            ("DESIGN_BUILD", "Design & Build"),
                        ],
                        default="LUMP_SUM",
                        max_length=30,
                    ),
                ),
                (
                    "original_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Original Contract Value (PGK)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("original_completion_date", models.DateField()),
                ("revised_completion_date", models.DateField(blank=True, null=True)),
                (
                    "liquidated_damages_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Liquidated Damages Rate (PGK/day)",
                    ),
                ),
                (
                    "dlp_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Defects Liability Period (months)"
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="Retention Percentage (%)",
                    ),
                ),
                (
                    "retention_cap_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Retention Cap (%)",
                    ),
                ),
                (
                    "payment_terms_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Payment Terms (days)"
                    ),
                ),
                (
                    "letter_of_award",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/loa/",
                        verbose_name="Letter of Award",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_number", models.CharField(editable=False, max_length=30)),
                ("description", models.TextField()),
                ("date_instructed", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTRUCTED", "Instructed"),
                            ("SUBMITTED", "Submitted"),
                            ("ASSESSED", "Assessed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="INSTRUCTED",
                        max_length=20,
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[("ADD", "Addition"), ("OMIT", "Omission")],
                        default="ADD",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount (PGK)"
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="variations/documents/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Variation",
                "verbose_name_plural": "Variations",
                "ordering": ["project", "ref_number"],
                "unique_together": {("project", "ref_number")},
            },
        ),
    ]
