# Generated by Django 6.0.6 on 2026-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='financial_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum PGK value this user can certify or record for financial actions', max_digits=14),
        ),
    ]
