# Generated by Django 6.0.6 on 2026-06-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_financial_approval_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('managing_director', 'Managing Director'), ('project_manager', 'Project Manager'), ('site_supervisor', 'Site Supervisor'), ('procurement_officer', 'Procurement Officer'), ('finance', 'Finance / Accounts'), ('document_controller', 'Document Controller'), ('auditor', 'Auditor / Funder Rep'), ('system_admin', 'System Administrator'), ('subcontractor', 'Subcontractor')], default='system_admin', max_length=30),
        ),
    ]
