# Generated by Django 5.2.15 on 2026-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notif_budget",
            field=models.BooleanField(
                default=True, verbose_name="Budget alert notifications"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notif_dsr",
            field=models.BooleanField(
                default=True, verbose_name="Daily Site Report notifications"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notif_ipc",
            field=models.BooleanField(
                default=True, verbose_name="IPC / payment notifications"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notif_milestone",
            field=models.BooleanField(
                default=True, verbose_name="Milestone due notifications"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notif_safety",
            field=models.BooleanField(
                default=True, verbose_name="Safety incident notifications"
            ),
        ),
    ]
