# Generated by Django 6.0.6 on 2026-06-05 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='match_exception_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='match_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='match_exception_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_match_exceptions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='match_exception_reason',
            field=models.TextField(blank=True),
        ),
    ]
