# Generated by Django 5.2.14 on 2026-06-01 04:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DSREquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "hours_idle",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "hours_breakdown",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "DSR Equipment Record",
                "verbose_name_plural": "DSR Equipment Records",
                "ordering": ["equipment"],
            },
        ),
        migrations.CreateModel(
            name="DSRIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("INSTRUCTION", "Site Instruction"),
                            ("RFI", "Request for Information (RFI)"),
                            ("MATERIAL_DELAY", "Material Delay"),
                            ("DESIGN", "Design / Drawing Issue"),
                            ("ACCESS", "Access / Clearance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("action_required", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "DSR Issue",
                "verbose_name_plural": "DSR Issues",
                "ordering": ["-date", "issue_type"],
            },
        ),
        migrations.CreateModel(
            name="DSRLabour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classification",
                    models.CharField(
                        help_text="e.g. Labourer, Carpenter, Electrician, Operator, Supervisor",
                        max_length=100,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[("PNG", "PNG National"), ("EXPAT", "Expatriate")],
                        default="PNG",
                        max_length=10,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "DSR Labour Record",
                "verbose_name_plural": "DSR Labour Records",
                "ordering": ["classification", "nationality"],
            },
        ),
        migrations.CreateModel(
            name="DSRMaterialDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "DSR Material Delivery",
                "verbose_name_plural": "DSR Material Deliveries",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DSRMaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_used", models.DecimalField(decimal_places=3, max_digits=10)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "DSR Material Usage",
                "verbose_name_plural": "DSR Material Usages",
                "ordering": ["material"],
            },
        ),
        migrations.CreateModel(
            name="DSRPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photo", models.ImageField(upload_to="dsr_photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("ACTIVITY", "Activity"),
                            ("AREA", "Site Area"),
                            ("EQUIPMENT", "Equipment"),
                            ("DEFECT", "Defect"),
                            ("SAFETY", "Safety"),
                            ("PROGRESS", "Progress"),
                            ("OTHER", "Other"),
                        ],
                        default="PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="GPS Latitude",
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="GPS Longitude",
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "DSR Photo",
                "verbose_name_plural": "DSR Photos",
                "ordering": ["taken_at"],
            },
        ),
        migrations.CreateModel(
            name="DSRVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("organization", models.CharField(max_length=150)),
                ("purpose", models.CharField(max_length=255)),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DSR Visitor",
                "verbose_name_plural": "DSR Visitors",
                "ordering": ["time_in"],
            },
        ),
        migrations.CreateModel(
            name="DailySiteReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dsr_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, unique=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "day_number",
                    models.IntegerField(
                        default=1,
                        help_text="Automatically calculated from project start date.",
                        verbose_name="Day Number from Project Start",
                    ),
                ),
                (
                    "weather_am",
                    models.CharField(
                        choices=[
                            ("SUNNY", "Sunny"),
                            ("PARTLY_CLOUDY", "Partly Cloudy"),
                            ("OVERCAST", "Overcast"),
                            ("LIGHT_RAIN", "Light Rain"),
                            ("HEAVY_RAIN", "Heavy Rain"),
                            ("STORM", "Storm / Severe Weather"),
                        ],
                        default="SUNNY",
                        max_length=20,
                        verbose_name="Weather (AM)",
                    ),
                ),
                (
                    "weather_pm",
                    models.CharField(
                        choices=[
                            ("SUNNY", "Sunny"),
                            ("PARTLY_CLOUDY", "Partly Cloudy"),
                            ("OVERCAST", "Overcast"),
                            ("LIGHT_RAIN", "Light Rain"),
                            ("HEAVY_RAIN", "Heavy Rain"),
                            ("STORM", "Storm / Severe Weather"),
                        ],
                        default="SUNNY",
                        max_length=20,
                        verbose_name="Weather (PM)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned for Revision"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked DSRs cannot be edited. Set automatically on approval.",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dsr_pdfs/",
                        verbose_name="Generated PDF",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsrs_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dsrs_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_site_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Site Report",
                "verbose_name_plural": "Daily Site Reports",
                "ordering": ["-date", "-dsr_number"],
            },
        ),
        migrations.CreateModel(
            name="DSRActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=500)),
                ("location_on_site", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("NOT_STARTED", "Not Started"),
                        ],
                        default="IN_PROGRESS",
                        max_length=15,
                    ),
                ),
                (
                    "quantity_achieved",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                (
                    "percent_complete",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Cumulative % Complete",
                    ),
                ),
                (
                    "constraints",
                    models.TextField(
                        blank=True,
                        help_text="For NOT_STARTED status: explain reason / constraint.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsr_activities",
                        to="resources.crew",
                    ),
                ),
                (
                    "dsr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="dsr.dailysitereport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DSR Activity",
                "verbose_name_plural": "DSR Activities",
                "ordering": ["pk"],
            },
        ),
    ]
