# Generated by Django 6.0.6 on 2026-06-05 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('dsr', '0002_initial'),
        ('ipc', '0001_initial'),
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
        ('quality', '0001_initial'),
        ('safety', '0001_initial'),
        ('schedule', '0002_programmerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsractivity',
            name='ipc_line_item',
            field=models.ForeignKey(blank=True, help_text='IPC line item supported by this DSR evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_activity_evidence', to='ipc.ipclineitem'),
        ),
        migrations.AddField(
            model_name='dsractivity',
            name='schedule_activity',
            field=models.ForeignKey(blank=True, help_text='Schedule activity supported by this DSR progress entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_activity_evidence', to='schedule.activity'),
        ),
        migrations.AddField(
            model_name='dsrissue',
            name='delay_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_issue_evidence', to='projects.delayevent'),
        ),
        migrations.AddField(
            model_name='dsrissue',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_issue_evidence', to='safety.incident'),
        ),
        migrations.AddField(
            model_name='dsrissue',
            name='ncr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_issue_evidence', to='quality.ncr'),
        ),
        migrations.AddField(
            model_name='dsrissue',
            name='rfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_issue_evidence', to='documents.rfi'),
        ),
        migrations.AddField(
            model_name='dsrmaterialusage',
            name='stock_ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_usage_evidence', to='procurement.stockledger'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='quality.defect'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='safety.incident'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='ncr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='quality.ncr'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='rfi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='documents.rfi'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='schedule_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='schedule.activity'),
        ),
        migrations.AddField(
            model_name='dsrphoto',
            name='wbs_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_photo_evidence', to='schedule.wbsactivity'),
        ),
    ]
