# Generated by Django 5.2.14 on 2026-06-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("LOGIN", "Logged In"),
                            ("LOGOUT", "Logged Out"),
                            ("SUBMIT", "Submitted"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("EXPORT", "Exported"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("changes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
