# Generated by Django 5.2.14 on 2026-06-01 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drawing_number", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ARCHITECTURAL", "Architectural"),
                            ("STRUCTURAL", "Structural"),
                            ("CIVIL", "Civil"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing / Hydraulics"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("scale", models.CharField(blank=True, max_length=50)),
                (
                    "current_revision",
                    models.CharField(
                        help_text='Current revision identifier, e.g. "A", "B", "C0".',
                        max_length=10,
                    ),
                ),
                ("current_revision_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IFC", "Issued for Construction"),
                            ("FOR_REVIEW", "Issued for Review"),
                            ("SUPERSEDED", "Superseded"),
                            ("FOR_INFO", "Issued for Information"),
                        ],
                        default="FOR_REVIEW",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="drawings/")),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawings",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing",
                "verbose_name_plural": "Drawings",
                "ordering": ["project", "discipline", "drawing_number"],
                "unique_together": {("project", "drawing_number")},
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="project_docs/")),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for company-wide templates.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_documents",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Document",
                "verbose_name_plural": "Project Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Correspondence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("date", models.DateField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("INCOMING", "Incoming"), ("OUTGOING", "Outgoing")],
                        default="INCOMING",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=200)),
                ("recipient", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("document", models.FileField(upload_to="correspondence/")),
                ("action_required", models.BooleanField(default=False)),
                ("action_due_date", models.DateField(blank=True, null=True)),
                ("response_date", models.DateField(blank=True, null=True)),
                ("is_responded", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondences",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondence",
                "verbose_name_plural": "Correspondence",
                "ordering": ["project", "-date"],
                "unique_together": {("project", "reference_number")},
            },
        ),
        migrations.CreateModel(
            name="DrawingRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("file", models.FileField(upload_to="drawings/revisions/")),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="documents.drawing",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_drawing_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing Revision",
                "verbose_name_plural": "Drawing Revisions",
                "ordering": ["drawing", "-date"],
                "unique_together": {("drawing", "revision")},
            },
        ),
        migrations.CreateModel(
            name="RFI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rfi_number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("date_raised", models.DateField()),
                ("subject", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("directed_to", models.CharField(max_length=200)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="rfi_attachments/"
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("response_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESPONDED", "Responded"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "schedule_impact_days",
                    models.IntegerField(
                        default=0, verbose_name="Schedule Impact (days)"
                    ),
                ),
                (
                    "cost_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Cost Impact (PGK)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfis",
                        to="documents.drawing",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfis",
                        to="projects.project",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raised_rfis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RFI",
                "verbose_name_plural": "RFIs",
                "ordering": ["project", "-date_raised"],
                "unique_together": {("project", "rfi_number")},
            },
        ),
        migrations.CreateModel(
            name="Submittal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submittal_number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                (
                    "submittal_type",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material Submittal"),
                            ("SHOP_DRAWING", "Shop Drawing"),
                            ("METHOD_STATEMENT", "Method Statement"),
                            ("SAMPLE", "Sample"),
                            ("CERTIFICATE", "Certificate"),
                        ],
                        default="MATERIAL",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("submitted_date", models.DateField()),
                ("document", models.FileField(upload_to="submittals/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_AS_NOTED", "Approved As Noted"),
                            ("REVISE_RESUBMIT", "Revise & Resubmit"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_date", models.DateField(blank=True, null=True)),
                ("revision", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submittals",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submittals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_submittals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submittal",
                "verbose_name_plural": "Submittals",
                "ordering": ["project", "-submitted_date"],
                "unique_together": {("project", "submittal_number")},
            },
        ),
    ]
