# Generated by Django 5.2.15 on 2026-06-11 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_distributioncontact_documenttransmittal"),
        ("projects", "0004_workpackage_created_by_workpackage_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocument",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_project_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("INTERNAL", "Internal"),
                    ("CONFIDENTIAL", "Confidential"),
                ],
                default="INTERNAL",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="document_number",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("FOR_REVIEW", "For Review"),
                    ("APPROVED", "Approved / Issued"),
                    ("SUPERSEDED", "Superseded"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("DOWNLOAD", "Download"), ("VIEW", "View")],
                        default="DOWNLOAD",
                        max_length=10,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.projectdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Access Log",
                "verbose_name_plural": "Document Access Logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentControlSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rfi_prefix", models.CharField(default="RFI", max_length=10)),
                ("submittal_prefix", models.CharField(default="SUB", max_length=10)),
                (
                    "correspondence_prefix",
                    models.CharField(default="CORR", max_length=10),
                ),
                ("transmittal_prefix", models.CharField(default="TRN", max_length=10)),
                ("document_prefix", models.CharField(default="DOC", max_length=10)),
                (
                    "number_padding",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Digits in the numeric part of references, e.g. 4 → RFI-0001.",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "include_project_code",
                    models.BooleanField(
                        default=False,
                        help_text="Include the project code in references, e.g. RFI-KC001-0001.",
                    ),
                ),
                (
                    "rfi_response_due_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Days before an unanswered RFI is flagged overdue.",
                    ),
                ),
                (
                    "submittal_review_due_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="Days before an unreviewed submittal is flagged overdue.",
                    ),
                ),
                (
                    "correspondence_action_due_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Default days allowed for correspondence requiring action.",
                    ),
                ),
                (
                    "require_document_approval",
                    models.BooleanField(
                        default=True,
                        help_text="New controlled documents and revisions must pass review before issue.",
                    ),
                ),
                (
                    "require_transmittal_acknowledgement",
                    models.BooleanField(
                        default=True,
                        help_text="Sent transmittals must be acknowledged by the recipient.",
                    ),
                ),
                (
                    "auto_supersede_on_new_revision",
                    models.BooleanField(
                        default=True,
                        help_text="Uploading a new revision automatically supersedes the previous one.",
                    ),
                ),
                (
                    "allowed_file_extensions",
                    models.CharField(
                        default="pdf,doc,docx,xls,xlsx,csv,dwg,dxf,jpg,jpeg,png,zip",
                        help_text="Comma-separated list of permitted file extensions.",
                        max_length=255,
                    ),
                ),
                (
                    "max_upload_size_mb",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Maximum upload size in megabytes."
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=15,
                    ),
                ),
                (
                    "log_document_access",
                    models.BooleanField(
                        default=True,
                        help_text="Record an access log entry each time a controlled document is downloaded.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave blank for the company-wide default settings.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_control_settings",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Control Settings",
                "verbose_name_plural": "Document Control Settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectDocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to="project_docs/revisions/")),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="documents.projectdocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_project_document_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Revision",
                "verbose_name_plural": "Document Revisions",
                "ordering": ["-created_at"],
                "unique_together": {("document", "version")},
            },
        ),
    ]
