# Generated by Django 5.2.14 on 2026-06-04 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ipc", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceCalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TCS", "OTML TCS"),
                            ("IRC", "IRC / Tax"),
                            ("RPNGC", "RPNGC / Government"),
                            ("SAFETY", "Safety"),
                            ("QUALITY", "Quality"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                (
                    "reminder_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Send reminder this many days before due date.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETE", "Complete"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived / N/A"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/calendar/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for company-wide compliance items.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Calendar Entry",
                "verbose_name_plural": "Compliance Calendar Entries",
                "ordering": ["due_date", "project"],
            },
        ),
        migrations.CreateModel(
            name="IRCTaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(db_index=True, max_length=30)),
                ("invoice_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "kemele_tinpng",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Kemele TINPNG"
                    ),
                ),
                (
                    "kemele_gst_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Kemele GST No."
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_address", models.TextField(blank=True)),
                (
                    "client_tinpng",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Client TINPNG"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default="0.10",
                        max_digits=5,
                        verbose_name="GST Rate",
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of works / services for this invoice"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="Net 30 days", max_length=100),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ipc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_invoices",
                        to="ipc.ipc",
                        verbose_name="Linked IPC",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IRC Tax Invoice",
                "verbose_name_plural": "IRC Tax Invoices",
                "ordering": ["project", "-invoice_date"],
                "unique_together": {("project", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="OTMLTCSReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_number", models.CharField(db_index=True, max_length=30)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("MILESTONE", "Milestone"),
                        ],
                        default="MONTHLY",
                        max_length=15,
                    ),
                ),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to OTML"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected / Revision Required"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "total_tcs_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "expenditure_to_date",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "expenditure_this_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "overall_progress_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Overall Physical Progress (%)",
                    ),
                ),
                (
                    "narrative",
                    models.TextField(blank=True, verbose_name="Progress Narrative"),
                ),
                (
                    "issues_risks",
                    models.TextField(blank=True, verbose_name="Issues & Risks"),
                ),
                (
                    "local_labour_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Local Labour % (PNG)",
                    ),
                ),
                (
                    "expat_labour_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Expatriate Labour %",
                    ),
                ),
                (
                    "local_materials_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Local Materials % (PNG-sourced)",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/tcs/"
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otml_tcs_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tcs_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTML TCS Report",
                "verbose_name_plural": "OTML TCS Reports",
                "ordering": ["project", "-period_to"],
                "unique_together": {("project", "report_number")},
            },
        ),
    ]
