# Generated by Django 6.0.6 on 2026-06-05 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('projects', '0002_projectmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='irctaxinvoice',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irctaxinvoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irctaxinvoice',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='irctaxinvoice',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='irctaxinvoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irctaxinvoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorityPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.CharField(choices=[('BUILDING_BOARD', 'Building Board'), ('PROVINCIAL', 'Provincial Authority'), ('LLG', 'District / LLG Authority'), ('FIRE', 'Fire Authority'), ('OCCUPANCY', 'Occupancy / Completion'), ('OTHER', 'Other Authority')], max_length=25)),
                ('permit_type', models.CharField(max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('INSPECTED', 'Inspected'), ('CERTIFIED', 'Certified / Occupancy Issued'), ('EXPIRED', 'Expired')], default='REQUIRED', max_length=15)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='compliance/authority_permits/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_permits', to='projects.project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'authority', 'permit_type'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCalendarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('TCS', 'OTML TCS'), ('IRC', 'IRC / Tax'), ('RPNGC', 'RPNGC / Government'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('OTHER', 'Other')], max_length=15)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ONCE', max_length=15)),
                ('default_reminder_days', models.PositiveIntegerField(default=14)),
                ('description', models.TextField(blank=True)),
                ('applies_to_government', models.BooleanField(default=True)),
                ('applies_to_private', models.BooleanField(default=True)),
                ('applies_to_maintenance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FunderReportPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funder_type', models.CharField(choices=[('OTML_TCS', 'OTML / TCS'), ('ADB', 'ADB (Asian Development Bank)'), ('WORLD_BANK', 'World Bank'), ('DFAT', 'DFAT (Australia Aid)'), ('PRIVATE', 'Private'), ('OTHER', 'Other')], max_length=20)),
                ('pack_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CLOSEOUT', 'Closeout'), ('ADHOC', 'Ad hoc')], default='MONTHLY', max_length=15)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=15)),
                ('narrative', models.TextField(blank=True)),
                ('pack_file', models.FileField(blank=True, null=True, upload_to='compliance/funder_packs/')),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_report_packs', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', '-period_to'],
            },
        ),
        migrations.CreateModel(
            name='LocalContentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('png_labour_count', models.PositiveIntegerField(default=0)),
                ('expat_labour_count', models.PositiveIntegerField(default=0)),
                ('local_supplier_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_supplier_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('local_subcontractor_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_subcontractor_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('png_material_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_material_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='compliance/local_content/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_content_records', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', '-period_to'],
            },
        ),
        migrations.CreateModel(
            name='PublicProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_number', models.CharField(db_index=True, max_length=80)),
                ('procurement_method', models.CharField(choices=[('OPEN_TENDER', 'Open Tender'), ('SELECT_TENDER', 'Selective Tender'), ('RFQ', 'Request for Quotation'), ('SOLE_SOURCE', 'Sole Source / Direct Award')], default='OPEN_TENDER', max_length=20)),
                ('procuring_entity', models.CharField(blank=True, max_length=255)),
                ('approval_reference', models.CharField(blank=True, max_length=120)),
                ('approval_history', models.TextField(blank=True)),
                ('evaluation_summary', models.TextField(blank=True)),
                ('probity_notes', models.TextField(blank=True)),
                ('bid_evaluation_file', models.FileField(blank=True, null=True, upload_to='compliance/procurement/')),
                ('award_notice_file', models.FileField(blank=True, null=True, upload_to='compliance/procurement/')),
                ('approval_file', models.FileField(blank=True, null=True, upload_to='compliance/procurement/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('AWARDED', 'Awarded')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_procurement_records', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', '-created_at'],
                'unique_together': {('project', 'tender_number')},
            },
        ),
    ]
