# Generated by Django 5.2.15 on 2026-06-11 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "compliance",
            "0002_irctaxinvoice_exported_at_irctaxinvoice_issued_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="irctaxinvoice",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.10"),
                max_digits=5,
                verbose_name="GST Rate",
            ),
        ),
    ]
