# Generated by Django 6.0.6 on 2026-06-05 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.CharField(db_index=True, editable=False, max_length=30)),
                ('submitted_date', models.DateField()),
                ('reason', models.TextField()),
                ('revised_start', models.DateField()),
                ('revised_end', models.DateField()),
                ('eot_days', models.PositiveIntegerField(default=0, verbose_name='EOT Days')),
                ('causation_summary', models.TextField(blank=True, help_text='Explain delay causation, entitlement, mitigation, and concurrency assessment.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='programme_revisions/')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programme_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delay_events', models.ManyToManyField(blank=True, help_text='Delay events supporting the programme revision or EOT claim.', related_name='programme_revisions', to='projects.delayevent')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='schedule.programme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme Revision',
                'verbose_name_plural': 'Programme Revisions',
                'ordering': ['programme', '-submitted_date', '-revision_number'],
                'unique_together': {('programme', 'revision_number')},
            },
        ),
    ]
