# Generated by Django 5.2.14 on 2026-06-01 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ITP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("trade_section", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itps",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ITP",
                "verbose_name_plural": "ITPs",
                "ordering": ["project", "title"],
            },
        ),
        migrations.CreateModel(
            name="ITPItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.IntegerField(default=1)),
                ("description", models.TextField()),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold Point"),
                            ("WITNESS", "Witness Point"),
                            ("REVIEW", "Review"),
                        ],
                        default="WITNESS",
                        max_length=10,
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        choices=[
                            ("CONTRACTOR", "Contractor"),
                            ("CONSULTANT", "Consultant"),
                            ("CLIENT", "Client"),
                        ],
                        default="CONTRACTOR",
                        max_length=15,
                    ),
                ),
                ("acceptance_criteria", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quality.itp",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ITP Item",
                "verbose_name_plural": "ITP Items",
                "ordering": ["itp", "sequence"],
                "unique_together": {("itp", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("inspector_name", models.CharField(max_length=150)),
                ("inspector_org", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL_PASS", "Conditional Pass"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="inspections/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_off_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itp_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_records",
                        to="quality.itpitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Record",
                "verbose_name_plural": "Inspection Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ncr_number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("trade_responsible", models.CharField(max_length=150)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                ("raised_date", models.DateField()),
                ("corrective_action_required", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("close_out_date", models.DateField(blank=True, null=True)),
                ("close_out_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itp_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked ITP item if triggered by a failed inspection.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs",
                        to="quality.itpitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncrs",
                        to="projects.project",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raised_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_ncr_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NCR",
                "verbose_name_plural": "NCRs",
                "ordering": ["project", "-raised_date"],
                "unique_together": {("project", "ncr_number")},
            },
        ),
        migrations.CreateModel(
            name="MaterialTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("CONCRETE_STRENGTH", "Concrete Strength"),
                            ("SOIL_COMPACTION", "Soil Compaction"),
                            ("WELD", "Weld Test"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("test_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("sample_reference", models.CharField(max_length=100)),
                (
                    "specified_value",
                    models.CharField(
                        help_text="Specified/required value with units, e.g. '25 MPa'",
                        max_length=100,
                    ),
                ),
                (
                    "actual_value",
                    models.CharField(
                        help_text="Actual measured value with units, e.g. '27.4 MPa'",
                        max_length=100,
                    ),
                ),
                ("passed", models.BooleanField(default=True)),
                (
                    "lab_certificate",
                    models.FileField(blank=True, null=True, upload_to="test_certs/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_tests",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-linked NCR if test failed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_tests",
                        to="quality.ncr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Test Result",
                "verbose_name_plural": "Material Test Results",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "defect_number",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("trade", models.CharField(max_length=100)),
                ("identified_date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("CONSTRUCTION", "Construction"),
                            ("DLP", "Defects Liability Period"),
                        ],
                        default="CONSTRUCTION",
                        max_length=15,
                    ),
                ),
                ("responsible_party", models.CharField(max_length=150)),
                ("target_rectification_date", models.DateField(blank=True, null=True)),
                (
                    "photo_before",
                    models.FileField(blank=True, null=True, upload_to="defect_photos/"),
                ),
                (
                    "photo_after",
                    models.FileField(blank=True, null=True, upload_to="defect_photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RECTIFIED", "Rectified"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("close_out_date", models.DateField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_defects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Defect",
                "verbose_name_plural": "Defects",
                "ordering": ["project", "-identified_date"],
                "unique_together": {("project", "defect_number")},
            },
        ),
    ]
