# Generated by Django 6.0.6 on 2026-06-05 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itpitem',
            name='hold_point_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_quality_hold_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itpitem',
            name='hold_point_released_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itpitem',
            name='witness_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_quality_witness_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itpitem',
            name='witness_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='closure_evidence',
            field=models.FileField(blank=True, null=True, upload_to='ncr_closure/'),
        ),
        migrations.AddField(
            model_name='ncr',
            name='corrective_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='preventive_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('inspection_date', models.DateField()),
                ('signed_off_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checklists_inspected', to=settings.AUTH_USER_MODEL)),
                ('itp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='quality.itp')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checklists_signed_off', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('acceptance_criteria', models.CharField(blank=True, max_length=500)),
                ('passed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='quality_checklists/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.inspectionchecklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
