from django.urls import path

from . import views

app_name = "documents"

urlpatterns = [
    path("", views.DocumentControlHomeView.as_view(), name="index"),
    # Document control settings
    path(
        "settings/",
        views.CompanyDocumentSettingsView.as_view(),
        name="company-settings",
    ),
    path(
        "projects/<int:project_pk>/settings/",
        views.ProjectDocumentSettingsView.as_view(),
        name="project-settings",
    ),
    path(
        "projects/<int:project_pk>/settings/reset/",
        views.ProjectDocumentSettingsResetView.as_view(),
        name="project-settings-reset",
    ),
    # Drawings
    path(
        "projects/<int:project_pk>/drawings/",
        views.DrawingListView.as_view(),
        name="drawing-list",
    ),
    path(
        "projects/<int:project_pk>/drawings/add/",
        views.DrawingCreateView.as_view(),
        name="drawing-create",
    ),
    path(
        "projects/<int:project_pk>/drawings/latest-ifc/",
        views.LatestIFCDrawingListView.as_view(),
        name="latest-ifc-list",
    ),
    path(
        "projects/<int:project_pk>/drawings/<int:pk>/",
        views.DrawingDetailView.as_view(),
        name="drawing-detail",
    ),
    path(
        "projects/<int:project_pk>/drawings/<int:pk>/edit/",
        views.DrawingUpdateView.as_view(),
        name="drawing-update",
    ),
    # Drawing Revisions
    path(
        "drawings/<int:drawing_pk>/revisions/add/",
        views.DrawingRevisionCreateView.as_view(),
        name="drawingrevision-create",
    ),
    # RFIs
    path(
        "projects/<int:project_pk>/rfis/",
        views.RFIListView.as_view(),
        name="rfi-list",
    ),
    path(
        "projects/<int:project_pk>/rfis/add/",
        views.RFICreateView.as_view(),
        name="rfi-create",
    ),
    path(
        "projects/<int:project_pk>/rfis/<int:pk>/",
        views.RFIDetailView.as_view(),
        name="rfi-detail",
    ),
    path(
        "projects/<int:project_pk>/rfis/<int:pk>/edit/",
        views.RFIUpdateView.as_view(),
        name="rfi-update",
    ),
    # Submittals
    path(
        "projects/<int:project_pk>/submittals/",
        views.SubmittalListView.as_view(),
        name="submittal-list",
    ),
    path(
        "projects/<int:project_pk>/submittals/add/",
        views.SubmittalCreateView.as_view(),
        name="submittal-create",
    ),
    path(
        "projects/<int:project_pk>/submittals/<int:pk>/edit/",
        views.SubmittalUpdateView.as_view(),
        name="submittal-update",
    ),
    # Correspondence
    path(
        "projects/<int:project_pk>/correspondence/",
        views.CorrespondenceListView.as_view(),
        name="correspondence-list",
    ),
    path(
        "projects/<int:project_pk>/correspondence/add/",
        views.CorrespondenceCreateView.as_view(),
        name="correspondence-create",
    ),
    path(
        "projects/<int:project_pk>/correspondence/<int:pk>/edit/",
        views.CorrespondenceUpdateView.as_view(),
        name="correspondence-update",
    ),
    # Project Documents
    path(
        "projects/<int:project_pk>/docs/",
        views.ProjectDocumentListView.as_view(),
        name="projectdoc-list",
    ),
    path(
        "projects/<int:project_pk>/docs/add/",
        views.ProjectDocumentCreateView.as_view(),
        name="projectdoc-create",
    ),
    path(
        "projects/<int:project_pk>/docs/export/",
        views.ProjectDocumentRegisterExportView.as_view(),
        name="projectdoc-export",
    ),
    path(
        "projects/<int:project_pk>/docs/<int:pk>/",
        views.ProjectDocumentDetailView.as_view(),
        name="projectdoc-detail",
    ),
    path(
        "projects/<int:project_pk>/docs/<int:pk>/edit/",
        views.ProjectDocumentUpdateView.as_view(),
        name="projectdoc-update",
    ),
    path(
        "projects/<int:project_pk>/docs/<int:pk>/revisions/add/",
        views.ProjectDocumentRevisionCreateView.as_view(),
        name="projectdoc-revision-create",
    ),
    path(
        "projects/<int:project_pk>/docs/<int:pk>/download/",
        views.ProjectDocumentDownloadView.as_view(),
        name="projectdoc-download",
    ),
    path(
        "projects/<int:project_pk>/docs/<int:pk>/action/<slug:action>/",
        views.ProjectDocumentTransitionView.as_view(),
        name="projectdoc-action",
    ),
    path(
        "projects/<int:project_pk>/distribution/",
        views.DistributionContactListView.as_view(),
        name="distribution-contact-list",
    ),
    path(
        "projects/<int:project_pk>/distribution/add/",
        views.DistributionContactCreateView.as_view(),
        name="distribution-contact-create",
    ),
    path(
        "projects/<int:project_pk>/distribution/<int:pk>/edit/",
        views.DistributionContactUpdateView.as_view(),
        name="distribution-contact-update",
    ),
    path(
        "projects/<int:project_pk>/transmittals/",
        views.DocumentTransmittalListView.as_view(),
        name="transmittal-list",
    ),
    path(
        "projects/<int:project_pk>/transmittals/add/",
        views.DocumentTransmittalCreateView.as_view(),
        name="transmittal-create",
    ),
    path(
        "projects/<int:project_pk>/transmittals/<int:pk>/",
        views.DocumentTransmittalDetailView.as_view(),
        name="transmittal-detail",
    ),
    path(
        "projects/<int:project_pk>/transmittals/<int:pk>/edit/",
        views.DocumentTransmittalUpdateView.as_view(),
        name="transmittal-update",
    ),
    path(
        "projects/<int:project_pk>/transmittals/<int:pk>/acknowledge/",
        views.TransmittalAcknowledgeView.as_view(),
        name="transmittal-acknowledge",
    ),
    # Company-wide templates
    path(
        "templates/",
        views.ProjectDocumentTemplatesView.as_view(),
        name="projectdoc-templates",
    ),
]
