# Generated by Django 6.0.6 on 2026-06-05 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STARTED', max_length=15)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('ACCOUNTING', 'Accounting'), ('PAYROLL', 'Payroll'), ('INVENTORY', 'Inventory')], max_length=20)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='READY', max_length=15)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='integrations/exports/')),
                ('message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_type', models.CharField(choices=[('CLIENT', 'Client'), ('FUNDER', 'Funder'), ('SUBCONTRACTOR', 'Subcontractor'), ('SUPPLIER', 'Supplier')], max_length=20)),
                ('organisation', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_documents', models.BooleanField(default=True)),
                ('can_submit_claims', models.BooleanField(default=False)),
                ('can_submit_deliveries', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_records', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'portal_type', 'organisation'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReadinessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('SECURITY', 'Security'), ('BACKUP', 'Backup'), ('MONITORING', 'Monitoring'), ('AUDIT', 'Audit'), ('PERFORMANCE', 'Performance'), ('OPERATIONS', 'Operations')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='readiness/evidence/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['area', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('EXECUTIVE_PACK', 'Executive Pack'), ('PORTFOLIO', 'Portfolio Report'), ('PROJECT_MONTHLY', 'Project Monthly Report'), ('ACCOUNTING', 'Accounting Export'), ('SAFETY', 'Safety Export')], max_length=30)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=15)),
                ('recipients', models.TextField(help_text='Comma-separated email recipients.')),
                ('next_run', models.DateField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('object_reference', models.CharField(blank=True, max_length=120)),
                ('client_payload', models.JSONField(blank=True, default=dict)),
                ('server_payload', models.JSONField(blank=True, default=dict)),
                ('resolution_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED_CLIENT', 'Resolved using client'), ('RESOLVED_SERVER', 'Resolved using server'), ('MERGED', 'Merged')], default='OPEN', max_length=25)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoQImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.CharField(max_length=30)),
                ('source_file', models.FileField(upload_to='boq/imports/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=15)),
                ('validation_summary', models.TextField(blank=True)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_valid', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_import_batches', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', '-created_at'],
                'unique_together': {('project', 'revision')},
            },
        ),
    ]
