# Generated by Django 5.2.14 on 2026-06-04 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BidEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tender_reference",
                    models.CharField(
                        max_length=100, verbose_name="Tender Reference / RFT Number"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("funder", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("tender_due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINAL", "Final"),
                            ("SUBMITTED", "Submitted"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("NO_BID", "No Bid"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "estimate_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "bid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Target Margin %",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="tender.bidestimate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bid Estimate",
                "verbose_name_plural": "Bid Estimates",
                "ordering": ["-tender_due_date"],
            },
        ),
        migrations.CreateModel(
            name="CostRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("STRUCTURAL", "Structural"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing"),
                            ("CARPENTRY", "Carpentry"),
                            ("FINISHES", "Finishes"),
                            ("PRELIMS", "Preliminaries"),
                            ("LABOUR", "Labour"),
                            ("PLANT", "Plant & Equipment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("NCD", "National Capital District"),
                            ("HIGHLANDS", "Highlands Region"),
                            ("MOMASE", "Momase Region"),
                            ("ISLANDS", "Islands Region"),
                            ("SOUTHERN", "Southern Region"),
                            ("NATIONAL", "National (All Regions)"),
                        ],
                        default="NATIONAL",
                        max_length=15,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Year the rate was recorded"
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. m², m³, LM, item, day", max_length=30
                    ),
                ),
                ("unit_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Verified for use in estimates"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this rate was derived from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_rates",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Rate",
                "verbose_name_plural": "Cost Rates",
                "ordering": ["trade", "description", "-year"],
            },
        ),
        migrations.CreateModel(
            name="BidEstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("STRUCTURAL", "Structural"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing"),
                            ("CARPENTRY", "Carpentry"),
                            ("FINISHES", "Finishes"),
                            ("PRELIMS", "Preliminaries"),
                            ("LABOUR", "Labour"),
                            ("PLANT", "Plant & Equipment"),
                            ("OTHER", "Other"),
                        ],
                        default="CIVIL",
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=30)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tender.bidestimate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_items",
                        to="tender.costrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bid Estimate Item",
                "verbose_name_plural": "Bid Estimate Items",
                "ordering": ["trade", "description"],
            },
        ),
        migrations.CreateModel(
            name="TenderArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_date", models.DateField(auto_now_add=True)),
                (
                    "original_contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "final_contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Margin %",
                    ),
                ),
                ("planned_duration_days", models.PositiveIntegerField(default=0)),
                ("actual_duration_days", models.PositiveIntegerField(default=0)),
                ("executive_summary", models.TextField(blank=True)),
                (
                    "key_scope",
                    models.TextField(blank=True, verbose_name="Key Scope of Works"),
                ),
                ("unique_challenges", models.TextField(blank=True)),
                (
                    "searchable_tags",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated tags for search: e.g. CONCRETE,ROADS,HIGHLAND",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_archive",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender Archive",
                "verbose_name_plural": "Tender Archives",
                "ordering": ["-archived_date"],
            },
        ),
        migrations.CreateModel(
            name="LessonsLearned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COST", "Cost"),
                            ("SCHEDULE", "Schedule"),
                            ("QUALITY", "Quality"),
                            ("SAFETY", "Safety"),
                            ("PROCUREMENT", "Procurement"),
                            ("CLIENT", "Client Relations"),
                            ("DESIGN", "Design"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("what_went_well", models.TextField(blank=True)),
                ("what_went_wrong", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.TextField(
                        help_text="Specific, actionable recommendation for next project."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_learned",
                        to="projects.project",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons_learned",
                        to="tender.tenderarchive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Learned",
                "verbose_name_plural": "Lessons Learned",
                "ordering": ["-created_at", "category"],
            },
        ),
        migrations.AddField(
            model_name="costrate",
            name="archive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_rates",
                to="tender.tenderarchive",
            ),
        ),
    ]
