# Generated by Django 5.2.14 on 2026-06-04 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("METHOD_STATEMENT", "Method Statement"),
                            ("CV", "Personnel CV"),
                            ("ORG_CHART", "Organisational Chart"),
                            ("CERTIFICATION", "Company Certification"),
                            ("PROFILE", "Company Profile / Capability Statement"),
                            ("TEMPLATE", "Document Template"),
                            ("CONTRACT_CLAUSE", "Contract Clause Library"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "trade_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank if applicable to all trades.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        upload_to="tender/documents/%Y/", verbose_name="File"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Current Version"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated search tags: e.g. CONCRETE,ROADS,ISO9001",
                        max_length=500,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender Document",
                "verbose_name_plural": "Tender Documents",
                "ordering": ["doc_type", "title"],
            },
        ),
    ]
