# Generated by Django 5.2.14 on 2026-06-01 04:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text='Cost code identifier, e.g. "01.CIVIL.EARTHWORKS"',
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("STRUCTURAL", "Structural"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing"),
                            ("CARPENTRY", "Carpentry"),
                            ("FINISHES", "Finishes"),
                            ("PRELIMINARIES", "Preliminaries"),
                            ("CONTINGENCY", "Contingency"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("is_contingency", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_codes",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Code",
                "verbose_name_plural": "Cost Codes",
                "ordering": ["code"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.CreateModel(
            name="BoQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_number",
                    models.CharField(
                        help_text='Hierarchical item number, e.g. "1.1.1"',
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("m2", "m²"),
                            ("m3", "m³"),
                            ("m", "m"),
                            ("nr", "nr"),
                            ("kg", "kg"),
                            ("t", "t"),
                            ("l", "l"),
                            ("hr", "hr"),
                            ("day", "day"),
                            ("lump", "lump"),
                            ("allow", "allow"),
                        ],
                        default="nr",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "unit_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "is_variation",
                    models.BooleanField(
                        default=False,
                        help_text="True if this item was added via a variation order.",
                    ),
                ),
                (
                    "trade_section",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil"),
                            ("STRUCTURAL", "Structural"),
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("PLUMBING", "Plumbing"),
                            ("CARPENTRY", "Carpentry"),
                            ("FINISHES", "Finishes"),
                            ("PRELIMINARIES", "Preliminaries"),
                            ("CONTINGENCY", "Contingency"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_items",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="projects.variation",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="budget.costcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoQ Item",
                "verbose_name_plural": "BoQ Items",
                "ordering": ["item_number"],
                "unique_together": {("project", "item_number")},
            },
        ),
        migrations.CreateModel(
            name="CostEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("COMMITTED", "Committed"), ("ACTUAL", "Actual")],
                        default="ACTUAL",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField()),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Invoice or Purchase Order number.",
                        max_length=100,
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="cost_entries/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cost_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_entries",
                        to="budget.boqitem",
                    ),
                ),
                (
                    "cost_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_entries",
                        to="budget.costcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Entry",
                "verbose_name_plural": "Cost Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subcontract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trade", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("scope", models.TextField()),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "retention_held",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total retention amount currently withheld (PGK).",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontracts",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontract",
                "verbose_name_plural": "Subcontracts",
                "ordering": ["company_name"],
            },
        ),
    ]
