# Generated by Django 6.0.6 on 2026-06-05 03:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='contingency_drawdown',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved contingency consumed by this cost code.', max_digits=14, verbose_name='Contingency Drawdown (PGK)'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='forecast_etc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Forecast remaining cost required to complete this cost code.', max_digits=14, verbose_name='Estimate to Complete (PGK)'),
        ),
        migrations.AddField(
            model_name='costcode',
            name='provisional_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allowance held against uncertain scope within this cost code.', max_digits=14, verbose_name='Provisional Sum (PGK)'),
        ),
    ]
