# Generated by Django 6.0.6 on 2026-06-05 03:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_costcode_contingency_drawdown_costcode_forecast_etc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(db_index=True, editable=False, max_length=30)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('submitted_date', models.DateField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('assessed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('retention_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('backcharge_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSESSED', 'Assessed'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='budget.subcontract')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcontract Claim',
                'verbose_name_plural': 'Subcontract Claims',
                'ordering': ['subcontract', '-submitted_date', '-claim_number'],
                'unique_together': {('subcontract', 'claim_number')},
            },
        ),
        migrations.CreateModel(
            name='SubcontractBackCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RECOVERED', 'Recovered'), ('WAIVED', 'Waived')], default='DRAFT', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backcharges', to='budget.subcontract')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('recovered_from_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_backcharges', to='budget.subcontractclaim')),
            ],
            options={
                'verbose_name': 'Subcontract Back-Charge',
                'verbose_name_plural': 'Subcontract Back-Charges',
                'ordering': ['subcontract', '-date'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateField()),
                ('quality_score', models.PositiveSmallIntegerField(default=3)),
                ('schedule_score', models.PositiveSmallIntegerField(default=3)),
                ('safety_score', models.PositiveSmallIntegerField(default=3)),
                ('commercial_score', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='budget.subcontract')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcontract Performance Review',
                'verbose_name_plural': 'Subcontract Performance Reviews',
                'ordering': ['subcontract', '-review_date'],
            },
        ),
    ]
