# Generated by Django 6.0.6 on 2026-06-08 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_subcontractclaim_subcontractbackcharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontract',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Login account for the subcontractor company's representative.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubcontractorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('shop_drawing', 'Shop Drawing'), ('method_statement', 'Method Statement'), ('risk_assessment', 'Risk Assessment / RAMS'), ('quality_plan', 'Quality Plan / ITP'), ('programme', 'Programme / Schedule'), ('insurance', 'Insurance / Compliance'), ('other', 'Other')], default='other', max_length=30)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='subcontractor_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected / Revise & Resubmit')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subcontractor_docs', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='budget.subcontract')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_subcontractor_docs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcontractor Document',
                'verbose_name_plural': 'Subcontractor Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
